project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.ipynb"

website:
  title: "Andre Personal Blog :)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/abarbosa94
      - icon: linkedin
        href: https://www.linkedin.com/in/barbosaandre
format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: language-switch.html
execute:
  freeze: auto


