project:
  type: website

website:
  title: "Andre Personal Blog :)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/abarbosa94
      - icon: linkedin
        href: https://www.linkedin.com/in/barbosaandre
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto


