"use strict";
const tags = {accuracy:"Meaning / accuracy",omission:"Omission",addition:"Addition",fluency:"Fluency",terminology:"Terminology",locale:"Target locale",style:"Style",formatting:"Formatting",reference_issue:"Reference issue",uncertain:"Uncertain",other:"Other"};
const state={items:[],filtered:[],currentId:null,meta:{},undo:null,saving:false};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"");
function current(){return state.items.find(x=>x.sample_id===state.currentId)}
function idx(){return state.filtered.findIndex(x=>x.sample_id===state.currentId)}
function setStatus(message){$("saveStatus").textContent=message}
function applyFilters(){const status=$("statusFilter").value,dir=$("directionFilter").value;state.filtered=state.items.filter(x=>(status==="all"||(status==="pending"?x.review_status!=="reviewed":x.review_status===status))&&(dir==="all"||x.direction===dir));if(!state.filtered.some(x=>x.sample_id===state.currentId))state.currentId=state.filtered[0]?.sample_id??null;render()}
function render(){const item=current(),reviewed=state.items.filter(x=>x.review_status==="reviewed").length,total=state.items.length;$("progressLabel").textContent=`${reviewed} of ${total} reviewed`;$("remainingLabel").textContent=`${total-reviewed} remain; ${state.items.filter(x=>x.review_status==="defer").length} deferred`;$("progressBar").style.width=`${total?reviewed/total*100:0}%`;$("emptyState").hidden=Boolean(item);$("reviewCard").hidden=!item;if(!item)return;
  $("sampleBadge").textContent=item.sample_id;$("directionBadge").textContent=item.direction==="en -> pt-BR"?"English to Portuguese":"Portuguese to English";$("statusBadge").textContent=item.review_status.replace("_"," ");$("positionLabel").textContent=`${idx()+1} / ${state.filtered.length}`;$("sourceText").textContent=item.source;$("referenceText").textContent=item.human_reference;$("candidateA").textContent=item.candidate_A;$("candidateB").textContent=item.candidate_B;$("candidateAPanel").classList.toggle("selected",item.choice_A_B_or_tie==="A");$("candidateBPanel").classList.toggle("selected",item.choice_A_B_or_tie==="B");
  document.querySelectorAll("[data-confidence]").forEach(b=>b.classList.toggle("active",b.dataset.confidence===item.confidence));const selected=new Set(item.failure_tags.split("|").filter(Boolean));document.querySelectorAll("[data-tag]").forEach(c=>c.checked=selected.has(c.dataset.tag));$("tagCount").textContent=selected.size?`(${selected.size})`:"";$("note").value=item.note;$("addToGolden").checked=item.add_to_golden==="true";$("validationMessage").hidden=true;$("undoButton").disabled=!state.undo;}
async function patch(changes,{advance=false,remember=true}={}){const item=current();if(!item||state.saving)return;const savedId=item.sample_id,before={};Object.keys(changes).forEach(k=>before[k]=item[k]);state.saving=true;setStatus("Saving...");try{const response=await fetch(`/api/items/${encodeURIComponent(item.sample_id)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)});const body=await response.json();if(!response.ok)throw new Error(body.error||"Save failed");Object.assign(item,body.item);if(remember)state.undo={id:item.sample_id,changes:before};setStatus("Saved");applyFilters();if(advance&&state.currentId===savedId)go(1,true)}catch(error){$("validationMessage").textContent=error.message;$("validationMessage").hidden=false;$("detailsPanel").open=true;setStatus("Not saved")}finally{state.saving=false}}
function go(delta,unresolved=false){if(!state.filtered.length)return;let pool=unresolved?state.items.filter(x=>x.review_status!=="reviewed"):state.filtered;if(!pool.length)return;let i=pool.findIndex(x=>x.sample_id===state.currentId);state.currentId=pool[(i+delta+pool.length)%pool.length].sample_id;render();window.scrollTo({top:0,behavior:"smooth"})}
function decide(choice){const item=current();if(!item)return;if(!item.confidence){$("validationMessage").textContent="Choose low, medium, or high confidence first.";$("validationMessage").hidden=false;return}patch({choice_A_B_or_tie:choice,review_status:"reviewed"},{advance:true})}
function syncDetails(){const selected=[...document.querySelectorAll("[data-tag]:checked")].map(x=>x.dataset.tag).join("|");patch({failure_tags:selected,note:$("note").value,add_to_golden:String($("addToGolden").checked)},{remember:false})}
async function init(){Object.entries(tags).forEach(([value,label])=>{const node=document.createElement("label");node.innerHTML=`<input type="checkbox" data-tag="${value}"> ${label}`;$("failureTags").append(node)});const response=await fetch("/api/items");if(!response.ok)throw new Error("Could not load review data");const body=await response.json();state.items=body.items;state.meta=body.meta;state.currentId=state.items.find(x=>x.review_status!=="reviewed")?.sample_id??state.items[0]?.sample_id;applyFilters();setStatus("Ready")}
document.addEventListener("click",e=>{const choice=e.target.closest("[data-choice]");if(choice)decide(choice.dataset.choice);const confidence=e.target.closest("[data-confidence]");if(confidence)patch({confidence:confidence.dataset.confidence},{remember:false});const template=e.target.closest("[data-template]");if(template){$("note").value=[$("note").value,template.dataset.template].filter(Boolean).join(" ");syncDetails()}});
$("statusFilter").addEventListener("change",applyFilters);$("directionFilter").addEventListener("change",applyFilters);$("previousButton").onclick=()=>go(-1);$("nextButton").onclick=()=>go(1);$("nextUnreviewed").onclick=()=>go(1,true);$("deferButton").onclick=()=>patch({review_status:"defer"},{advance:true});$("clearFilters").onclick=()=>{$("statusFilter").value="all";$("directionFilter").value="all";applyFilters()};$("shortcutsButton").onclick=()=>$("shortcutsDialog").showModal();$("undoButton").onclick=()=>{if(!state.undo)return;const u=state.undo;state.currentId=u.id;state.undo=null;patch(u.changes,{remember:false})};$("failureTags").addEventListener("change",syncDetails);$("addToGolden").addEventListener("change",syncDetails);$("note").addEventListener("change",syncDetails);
document.addEventListener("keydown",e=>{if(e.target.matches("textarea,select,input"))return;const key=e.key.toLowerCase();if(key==="a"||key==="b")decide(key.toUpperCase());else if(key==="t")decide("tie");else if(key==="d")$("deferButton").click();else if(key==="n"||e.key==="ArrowRight")go(1);else if(key==="p"||e.key==="ArrowLeft")go(-1);else if(key==="u")$("undoButton").click();else if(["l","m","h"].includes(key))patch({confidence:{l:"low",m:"medium",h:"high"}[key]},{remember:false});else if(e.key==="?")$("shortcutsDialog").showModal()});
init().catch(error=>{setStatus(error.message);$("emptyState").hidden=false;$("emptyState").querySelector("h2").textContent=error.message});
